// Re-export all types from the core SDK for backward compatibility
export type {
  Player,
  Bullet,
  Enemy,
  PlayerScore,
  GameOverSummary,
  GameState,
  ServerMessage,
  ClientMessage,
  StateMessage,
  WelcomeMessage,
  ErrorMessage,
  MatchEndedMessage,
  MoveMessage,
  StopMessage,
  ShootMessage,
  PauseMessage,
  ResumeMessage,
  ExitMessage,
} from '@/core'
